### PR TITLE
 #167606036  Fix database schema bug

### PR DESCRIPTION
**Pull request by Nennyfills**
#### What does this PR do?
This pull request fixes the bug in the database schema

#### Description of Task to be completed
- Add default UUID number to the migration files
- References all foreign key in the migration files
- Add Votes table with a field upvote of data type of boolean
- Add seed for users and articles
- Remove redundant tables

#### How should this be manually tested?
- git clone this branch
- run `npm db:migrate` to migrate the database schema
- run `npm db:undo` to revert the database schema

#### Any Background Context You want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#167606036](https://www.pivotaltracker.com/story/show/167606036)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by Merkll — COMMENTED** [review]
I pulled the branch and effected some changes. You can check my commit to see changes.

**Review by Merkll — APPROVED** [review]

**Review by Bastieno — APPROVED** [review]
Good job @Merkll @Nennyfills

**Comment by Nennyfills** [comment]
> I pulled the branch and effected some changes. You can check my commit to see changes.

Seen, nice one!

**Review by iverenshaguy — CHANGES_REQUESTED** [review]
Make sure your PR title and commit messages adhere to our team convention

**Review by iverenshaguy — APPROVED** [review]
Good job

**Pull request merged**
