### PR TITLE
#167377528 Integrate HoundCI with badge attached to README

### PR DESCRIPTION
**Pull request by kennyedward**
#### What does this PR do?
This Pull Request sets up HoundCI and also adds HoundCI's badge to the README file

#### Description of Task to be completed

- Integrate HoundCI with Repo
- add configuration to .hound.yml file
- add houndci badge to README

#### How should this be manually tested?
N/A

#### Any Background Context You want to provide?
HoundCI is an automated code review for GitHub pull requests

#### What are the relevant pivotal tracker stories?

[#167377528](https://www.pivotaltracker.com/story/show/167377528)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by Nennyfills — APPROVED** [review]
Nice

**Review by Merkll — APPROVED** [review]
Setup Looks cool

**Review by Jonathan4github — APPROVED** [review]

**Review by ibkadeeko — APPROVED** [review]
Looks good to me

**Review by iverenshaguy — APPROVED** [review]
LGTM

**Comment by iverenshaguy** [comment]
You have 2 commits that are exactly the same thing and then another commit that starts with Merge... Please ensure this doesn't happen again.

**Comment by kennyedward** [comment]
Alright.
I'll ensure it doesn't happen again going forward.

**Pull request merged**
