### PR TITLE
#167377524 Setup Travis CI with Badges

### PR DESCRIPTION
**Pull request by Merkll**
setup travis-ci with coveralls and code climate for test reporting/coverage and maintainablity
#### What does this PR do?
Setup Travis CI for continuous Integration with code coverage services integration
#### Description of Task to be completed
* integrate travis-ci with repo
* create code coverage using coveralls and code climate
#### How should this be manually tested?
N/A

#### Any Background Context You want to provide?
None
#### What are the relevant pivotal tracker stories?

[#167377524](https://pivotaltracker.com/story/show/story-id), [#167377531](https://pivotaltracker.com/story/show/story-id)

#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by Bastieno — COMMENTED** [review]
This looks good.

**Comment by successgilli** [comment]
I believe this should work.
nice work.

**Review by successgilli — COMMENTED** [review]
looks good

**Comment by iverenshaguy** [comment]
Why was this closed? @Merkll

**Pull request closed without merging**
